version: '3'

services:
  mailio-nft-bridge:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: mailio-nft-bridge-prod
    command: [ "/app/main", "--config", "/config/conf.yml" ]
    volumes:
      - /home/igor/Downloads/nftbridgedata:/data:rw
      - ./../../conf-prod.yml:/config/conf.yml
    ports:
      - '8080:8080'
