version: '3'

services:
  mailio-nft-bridge:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: mailio-nft-bridge
    command: [ "/app/main", "--config", "/config/conf.yml" ]
    volumes:
      - ~/.dataprod:/data:rw
      - ./../../conf-prod.yml:/config/conf.yml
    ports:
      - '8081:8080'
